### ISSUE TITLE
Can't delete schools

### ISSUE THREAD

**Issue by lhueneke** [VillageScribeAssociation/awarenet#416]
Whenever I try to delete a school, I get the following error message:
![screenshot from 2016-11-07 15-07-32](https://cloud.githubusercontent.com/assets/20024663/20059135/4edf6578-a4fd-11e6-8aa3-743aa5de1806.png)

**Comment by AMWertlen** [comment]
Can you specify which school you tried to delete, please?

**Comment by lhueneke** [comment]
I tried two different ones. There is duplicates of Archie Mbolekwa and Grahamstown Adventists.

**Comment by AMWertlen** [comment]
This is on purpose. If there was activity at a school you may not delete it any longer, because you would be deleting content and backend information. 

I see that there was very little activity at http://awarenet.eu/schools/Seventh-Day-Adventist-School and http://awarenet.eu/schools/Archie-Mbolekwa-S.P.S. 

You can hide them by going into edit mode and selecting "hidden yes". There will be no longer visible for learners.

**Comment by lhueneke** [comment]
Ah ok that makes sense, thanks
